// Master Services Agreement text, transcribed from the official packet
// "MSA FINAL Spanish.pdf" (CONTRATO MAESTRO DE SERVICIO, pages 3–11).
//
// NOTE: This is a faithful transcription of the source PDF and should receive a
// final legal proofread against the signed original before launch. The source
// contains some section-numbering inconsistencies (e.g. the jump from §3 to §5,
// two §6 headings); they are preserved here as-is rather than silently "fixed."
//
// The Vendor Information Sheet (p.1) and ACH Enrollment (p.2) from the packet
// are NOT part of this displayed agreement text — they are collected as form
// fields. Governing law: Puerto Rico. Disputes: mediation then binding
// arbitration (FAA).

export const MSA_TITLE = "Contrato Maestro de Servicio";

export const MSA_TEXT_ES = `CONTRATO MAESTRO DE SERVICIO

Este Acuerdo Marco de Servicio (Acuerdo) es entre Byrdson Services, LLC. (Contratista General), y el Subcontratista identificado en la Hoja de Información del Proveedor de este paquete. El Contratista General y el Subcontratista han celebrado este acuerdo para confirmar los términos y condiciones bajo los cuales el Subcontratista puede realizar trabajos para el Contratista General. De vez en cuando, el Contratista General podrá solicitar al Subcontratista que realice trabajos en uno o más proyectos relacionados con la construcción de viviendas o edificios (Proyectos). Algunos de estos Proyectos pueden realizarse de conformidad con un "Contrato Principal" entre el Contratista General y su(s) "Cliente(s)". Cuando corresponda, los Términos y Condiciones de dicho Contrato Principal se incorporan a este acuerdo, en su totalidad, y el Subcontratista está obligado ante el Contratista General de la misma manera para todas las obligaciones que el Contratista General está obligado ante su(s) Cliente(s). El propietario de la propiedad en la que se realizará dicha construcción se denomina en el presente documento el "Propietario".

POR LO TANTO, en consideración de los convenios, términos y condiciones establecidos en este documento y por otras contraprestaciones buenas y valiosas, cuyo recibo y suficiencia reconoce el abajo firmante, el Contratista General y el Subcontratista acuerdan lo siguiente:

1. TRABAJO
El trabajo o los materiales (colectivamente, el Trabajo) que debe suministrar el Subcontratista incluye toda la mano de obra y los materiales proporcionados a solicitud del Contratista General desde y después de la fecha de este Acuerdo. Este Acuerdo entrará en vigor a partir de su fecha y continuará hasta que cualquiera de las partes lo rescinda mediante notificación por escrito a la otra parte con treinta (30) días de antelación; las obligaciones y garantías del Subcontratista seguirán vigentes después de la terminación respecto de todo el Trabajo suministrado antes de la terminación. Excepto por las órdenes de cambio, el Subcontratista acepta cumplir con todas las Cotizaciones de Oferta y/u Órdenes de Trabajo/Órdenes de Compra por un período de noventa (90) días a partir de la fecha de cada presentación.

2. DOCUMENTOS DEL CONTRATO
a. DOCUMENTOS DEL CONTRATO: Este Acuerdo, el Acuerdo entre el Contratista General, el Propietario y su(s) Cliente(s), si corresponde, junto con todas las órdenes de trabajo, ofertas, fianzas, órdenes de cambio o conjuntos completos de planes de construcción (incluyendo planos de cimientos, estructura, planta, elevación, detalles y especificaciones aplicables), constituirán la totalidad de los Documentos del Contrato, y no existen otros acuerdos, orales o escritos, entre las partes, excepto las garantías del Subcontratista bajo cualquier acuerdo anterior o contemporáneo con el Contratista General, las cuales se incorporan como referencia para todos los fines.
b. PLANOS Y ESPECIFICACIONES: El Subcontratista acepta leer y familiarizarse con todos los planos y especificaciones relevantes antes de iniciar cualquier Trabajo. El Subcontratista será el único responsable de toda la construcción bajo este Acuerdo, incluidas las técnicas, secuencias, procedimientos y medios de coordinación, y deberá realizar todo el trabajo de manera buena y profesional.
c. PEDIDOS DE CAMBIO: El Contratista General se reserva el derecho de ordenar cambios en el Trabajo (adiciones, eliminaciones o modificaciones) sin invalidar este Acuerdo, con ajustes correspondientes en los pagos. Todos los cambios serán autorizados mediante una Orden de Cambio escrita firmada por el Contratista General. La orden de cambio será presentada por el Contratista General al Programa DEO para su aprobación. Si el DEO aprueba la orden de cambio antes del punto de inspección del 50%, a los subcontratistas se les pagará el 90% del monto de Xactimate aprobado; si se aprueba después del 50%, se pagará en el sorteo final del monto Xactimate aprobado. Una vez recibida la aprobación por escrito del DEO, el subcontratista puede comenzar a trabajar.

3. PAGOS
a. DESEMPEÑO OPORTUNO: No se adeudarán pagos a menos y hasta que el Subcontratista haya realizado y entregado oportunamente todos los Trabajos solicitados, el Contratista General haya tenido oportunidad razonable de inspeccionar, haya recibido una factura identificando el Trabajo y haya recibido renuncias de gravamen válidas ejecutadas por el Subcontratista.
b. El subcontratista debe facturar dentro de las 2 semanas posteriores al trabajo completado e inspeccionado por el municipio y el representante de Byrdson Services. No facturar dentro de 2 semanas causará una multa administrativa del 3% a cada factura.
c. El subcontratista no puede presentar un gravamen mecánico sobre la propiedad por falta de facturación dentro de las 2 semanas posteriores a la inspección y obra terminada.
d. Los subcontratistas deben enviar por correo electrónico la confirmación de todas las inspecciones a ops@byrdsonservices.com tan pronto como se soliciten.
e. Si están disponibles mediante inspección de la ciudad, los subcontratistas deben solicitar inspecciones y permanecer en el lugar de trabajo en el momento de la inspección para verificar que se hayan pasado todas las inspecciones.
f. Si no se pasa la inspección, el problema debe corregirse el mismo día e inspeccionarse al día siguiente hábil. El contratista es responsable de cualquier tarifa asociada con inspecciones fallidas.
g. El subcontratista es responsable del pago de todas las inspecciones fallidas causadas por el subcontratista.
h. A los subcontratistas se les cobrará $150.00 por día de pérdida de tiempo de construcción debido a cada inspección fallida.
i. GARANTÍA PERSONAL: Los propietarios principales abajo firmantes del Subcontratista garantizarán personalmente el pago completo y puntual de todas las sumas adeudadas a empleados, agentes, subcontratistas, proveedores de materiales y de mano de obra. El Subcontratista y los propietarios principales no permitirán gravámenes sobre la propiedad objeto del Trabajo, pagarán o liberarán inmediatamente dichos gravámenes, y defenderán, indemnizarán y eximirán de responsabilidad al Contratista General, sus Clientes y al Propietario de cualquier reclamo relacionado con gravámenes.
j. PAGOS RETENIDOS O REDUCIDOS PARA CUBRIR LA PÉRDIDA: El Subcontratista acepta que los pagos pueden ser retenidos, y todos los costos incurridos por el Contratista General se cargarán al dinero adeudado al Subcontratista, si: (i) el trabajo es defectuoso y no se repara; (ii) el subcontratista no paga puntualmente a sus empleados, agentes o subcontratistas; (iii) no paga por mano de obra, materiales o equipos de terceros; (iv) no mantiene el seguro requerido; (v) otro subcontratista resulta perjudicado por un acto del subcontratista; (vi) se presentan reclamos o gravámenes por falta de pago; (vii) se presentan reclamaciones contra el Contratista General o el Propietario por las que el Subcontratista es responsable; (viii) los Trabajos no avanzan satisfactoriamente; (ix) el Contratista General cree razonablemente que el Trabajo no se completará conforme al Acuerdo; (x) el subcontratista no realiza el servicio de garantía; (xi) el Contratista General es multado por una agencia gubernamental por causa del Subcontratista; (xii) el subcontratista no presenta oportunamente facturas detalladas; o (xiii) el subcontratista hace una tergiversación material en cualquier solicitud de pago.
k. VERIFICACIÓN DE PAGO: El subcontratista cumplirá con los requisitos de este acuerdo y, al solicitar pago de materiales, proporcionará copias de conocimientos de embarque, facturas, recibos de entrega u otras pruebas de la ubicación y valor de los materiales.
l. PAGO POR TRABAJO INCOMPLETO: Si el Subcontratista es despedido o cesa voluntariamente el Trabajo antes de completar una Unidad de Vivienda, se pagará por el Trabajo completado satisfactoriamente a discreción del Contratista General y sin recurso del Subcontratista. El Subcontratista proporcionará toda la documentación solicitada dentro de las veinticuatro (24) horas.
m. NO RENUNCIA: El pago de cualquier suma no constituirá aprobación del Trabajo ni renuncia a los derechos del Contratista General de recuperar dichos pagos o retener pagos futuros.
n. RETENCIÓN: El Contratista General tendrá derecho a retener el diez por ciento (10%) de cada pago por el Trabajo realizado satisfactoriamente. Los fondos retenidos se pagarán treinta y cinco (35) días después de la aceptación final del Trabajo y de la recepción de las renuncias de gravamen válidas. Este monto de retención podrá ser retenido de conformidad con §53.101 et seq. del Código de Propiedad de Puerto Rico.

5. IMPUESTOS
a. El Subcontratista será el único responsable del pago de los impuestos de sus empleados que surjan de la ejecución de este Acuerdo, y deberá cumplir con todas las leyes estatales y federales aplicables (salarios, impuestos, seguros y compensación laboral). El Contratista General, su(s) Cliente(s) y el Estado de Puerto Rico no serán responsables del pago de impuestos ni de la provisión de seguro de desempleo, compensación laboral o beneficios.
b. El Subcontratista indemnizará, defenderá y eximirá de responsabilidad al Contratista General, su(s) Cliente(s), el Estado de Puerto Rico y/o sus funcionarios de toda responsabilidad relacionada con la obligación tributaria, el seguro de desempleo o la compensación laboral. El Subcontratista no resolverá ninguna demanda relacionada sin el consentimiento previo por escrito del Contratista General, su Cliente y el Procurador General de Puerto Rico.

6. SEGURO REQUERIDO
a. GENERALMENTE: El Subcontratista, a su exclusivo costo, adquirirá y mantendrá vigente durante la duración de cualquier Orden de trabajo el seguro por los montos y requisitos especificados. El seguro estará vigente antes del comienzo del trabajo. El seguro del Subcontratista se aplicará con carácter primario. Los límites generales agregados de la póliza de Responsabilidad General Comercial se aplicarán por proyecto, y la póliza de automóvil se aplicará a "cualquier automóvil".
b. APROBACIÓN: La aprobación previa de las pólizas por el Contratista General es condición previa a cualquier pago, y el seguro debe presentarse para revisión y aprobación antes del comienzo del trabajo.
c. COBERTURA CONTINUA: La aprobación de cambios en la cobertura constituirá una condición continua de este Acuerdo.
d. RENOVACIÓN: El Subcontratista proporcionará certificados de renovación o reemplazo no menos de treinta (30) días antes del vencimiento.
e. RESPALDO DE SEGURO ADICIONAL: El Contratista General y, si corresponde, su(s) Cliente(s) y sus funcionarios serán nombrados como asegurados adicionales para toda responsabilidad que surja bajo una Orden de Trabajo, excepto en pólizas de Compensación de Trabajadores y Responsabilidad Profesional. Se debe presentar un endoso de asegurado adicional original firmado.
f. SUBROGACIÓN: Cada póliza (excepto Responsabilidad Profesional) deberá prever una renuncia de subrogación a favor del Contratista General, y será emitida por compañías autorizadas en Puerto Rico, calificadas por A.M. Best como "A" o mejor.
g. ENDOSO DE CANCELACIÓN: Cada póliza deberá endosarse para especificar que no se cancelará ni reducirá materialmente sin aviso previo por escrito de treinta (30) días al Contratista General (diez (10) días por falta de pago de prima).
h. RIESGO DEL CONSTRUCTOR: Las disposiciones de esta sección no obligan al Contratista General a contratar seguro en beneficio del Subcontratista.
i. BONOS: El Subcontratista deberá proporcionar todas las garantías, bonos e instrucciones que requieran las especificaciones y sean necesarios para la finalización del Trabajo.

6. COMPENSACIÓN LABORAL / SEGURO DE DESEMPLEO
a. DEFINICIONES: "Certificado de Cobertura" significa una copia de un certificado de seguro o de autoridad para autoasegurarse emitido por la División de Compensación para Trabajadores del Departamento de Seguros de Puerto Rico. "Cobertura" significa seguro de compensación para trabajadores que cumple con el Código Laboral de Puerto Rico.
b. COBERTURA REQUERIDA: El Subcontratista deberá brindar cobertura conforme al Código Laboral de Puerto Rico para todos sus empleados durante la duración del proyecto, y proporcionar un certificado de cobertura al Contratista General antes de que se le adjudique la Obra y antes de acceder a la Propiedad. Si la cobertura vence durante el Proyecto, debe presentar un nuevo certificado antes del fin del período.
c. El subcontratista exigirá contractualmente a cada persona con la que contrate que proporcione y mantenga la cobertura correspondiente y los certificados requeridos.
d. Al firmar este acuerdo, el Subcontratista representa que todos sus empleados estarán cubiertos por compensación para trabajadores durante la duración del Proyecto. Proporcionar información falsa puede someter al Subcontratista a sanciones administrativas, penales o civiles.
e. El incumplimiento de estas disposiciones constituye incumplimiento de contrato que da derecho al Contratista General a declarar nulo el Acuerdo si no se subsana dentro de los cinco (5) días de la notificación.
f. Si no se suscriben pólizas por los montos de §6.a, el Subcontratista deberá tener seguro general o de responsabilidad en exceso por la diferencia.
g. El Contratista General tendrá derecho a recibir copias de las pólizas y endosos.

7. DECLARACIONES Y PACTOS DEL SUBCONTRATISTA
El Subcontratista acepta: (a) prestar el Trabajo con diligencia; (b) realizar la Obra de manera minuciosa y profesional; (c) cumplir plenamente con este Acuerdo y todas las leyes aplicables; (d) cumplir o superar las especificaciones del Contratista General o los más altos estándares de la industria; (e) proporcionar equipos de trabajo no menos de seis (6) días por semana si se solicita; (f) proceder con la ejecución oportuna independientemente de huelgas o movimientos laborales; (g) proporcionar evidencia de instalación conforme a las recomendaciones del fabricante y transferir las garantías al Propietario; (h) presentar autorizaciones de mano de obra y/o materiales ejecutadas antes del pago; (i) proporcionar copia de cualquier licencia para hacer negocios en el municipio/estado del Proyecto; (j) asegurar y proteger sus materiales y trabajos, asumiendo todas las pérdidas/daños hasta la aceptación final; y (k) notificar por escrito cualquier superficie o trabajo insatisfactorio antes de aplicar su trabajo.

8. MANO DE OBRA Y MATERIALES
a. GARANTÍAS: El Subcontratista declara tener suficiente habilidad, experiencia y conocimiento. Garantiza que todo el Trabajo se realizará de manera buena y profesional, apto para los fines previstos, y que todos los equipos y materiales serán nuevos (salvo especificación contraria), de buena calidad y libres de defectos. El Subcontratista garantiza que toda la mano de obra y materiales estarán libres de defectos por un período proporcional a la Garantía limitada expresa para el hogar otorgada al Propietario. En ausencia de dicha garantía, el Subcontratista garantiza que toda la mano de obra estará libre de defectos por tres (3) años y todos los materiales por once (11) años desde la finalización del Trabajo. El Subcontratista cede al Contratista General todas las garantías de los fabricantes y proporcionará todos los certificados, datos de prueba u otra información requerida por cualquier municipio, entidad gubernamental, FHA, VA, inspector o ingeniero.
b. CONTRATO DE SERVICIO DE GARANTÍAS: Todas las garantías sobrevivirán a este Acuerdo si se rescinde o expira antes del fin del período de garantía aplicable.
c. RIESGO DE PÉRDIDA: El Subcontratista es el único responsable del riesgo de pérdida, robo o daño a sus materiales, suministros, equipos y herramientas hasta que la instalación sea completada y aprobada por el Contratista General.
d. PROGRAMACIÓN: El subcontratista es responsable ante el superintendente de la programación del trabajo y/o la entrega de materiales; cualquier directiva de la oficina central del Contratista General prevalecerá en caso de conflicto.

9. MATERIALES Y MANO DE OBRA
a. Todo el Trabajo se ejecutará de manera profesional conforme a los Documentos del Contrato, completo y de acuerdo con las prácticas aprobadas; todos los materiales y equipos incorporados serán nuevos salvo especificación contraria.
b. Desde la aceptación final, el Subcontratista garantiza su Trabajo contra todos los defectos de materiales o mano de obra por el mayor de: (i) un (1) año desde la finalización y aceptación; (ii) cualquier período de garantía requerido por la jurisdicción; o (iii) según lo requiera cualquier garantía legal/regulatoria de un programa gubernamental (p. ej., "garantías 1, 2, 10").

10. TRABAJO DEFECTUOSO
a. INSPECCIÓN: El Contratista General y su(s) Cliente(s) tienen autoridad para rechazar y condenar el Trabajo que no cumpla con el Contrato Principal y ordenar su remoción y reemplazo.
b. REPARACIÓN: Notificado de Trabajo Defectuoso, el Subcontratista hará las reparaciones dentro de las ocho (8) horas en caso de emergencia y dentro de las cuarenta y ocho (48) horas en casos no urgentes, asumiendo el costo total. El Contratista General determinará a su discreción si constituye una emergencia. La falta de corrección dentro de estos tiempos constituirá un incumplimiento.
c. REPETICIÓN DE INSPECCIONES: El costo de las inspecciones de seguimiento por trabajo no completado satisfactoriamente correrá a cargo del Subcontratista.

11. TIEMPO DE PRESENTACIÓN / RETRASOS
a. El Subcontratista comenzará el Trabajo lo antes posible y lo realizará con prontitud y a una velocidad que no cause retrasos.
b. El Subcontratista completará primero la parte que el Contratista General desea, se mantendrá al día con el cronograma de progreso y completará su Trabajo dentro del tiempo original más cualquier extensión permitida por el Propietario.
c. El Subcontratista estará obligado por las mismas disposiciones de indemnización que vinculan al Contratista General ante su(s) Cliente(s) o Propietario.
d. El Contratista General no será responsable ante el Subcontratista por retrasos resultantes de actos, negligencia o incumplimiento del Propietario, incendio, otros siniestros, huelgas, caso fortuito u otras causas fuera de su control.
e. El Subcontratista reembolsará al Contratista General cualquier pérdida, daño o gasto adicional causado por el incumplimiento del Subcontratista.
f. Al vencimiento o terminación, el Subcontratista desalojará de inmediato el lugar de trabajo y retirará todos los suministros, herramientas o equipos distintos de los pagados por el Contratista General.

12. CUMPLIMIENTO DE LEYES, ORDENANZAS, CÓDIGOS DE CONSTRUCCIÓN Y DOCUMENTOS DEL CONTRATO
a. CUMPLIMIENTO: Antes de realizar cualquier Trabajo, el Subcontratista se familiarizará con el Proyecto, los planos, especificaciones, la propiedad y las leyes, ordenanzas y códigos de construcción aplicables, incluyendo la Ley Davis-Bacon (para reparaciones de propiedades que contengan más de ocho (8) unidades) y la sección 3 de la Ley de Vivienda y Desarrollo Urbano de 1968. Si algún Documento del Contrato difiere de las leyes aplicables, el Subcontratista lo notificará por escrito antes de iniciar el Trabajo.
b. LICENCIA DE COMERCIO: El subcontratista cumplirá con la ley estatal relacionada con la licencia requerida de comerciantes, contratistas, materialistas, proveedores y trabajadores. Si el Subcontratista o cualquiera de sus Subcontratistas pierde su licencia, contratará o reemplazará de inmediato a un proveedor autorizado sin costo adicional para el Contratista General.

13. RESIDUOS
El Subcontratista mantendrá el local de trabajo y los caminos anejos libres de materiales de desecho y basura ocasionados por la Obra, los retirará al finalizar el Trabajo junto con todas las herramientas y equipos, realizará la limpieza general al finalizar, trasladará todos los materiales a un lugar designado por el Contratista General, y no quemará ningún material ni desperdicio en la propiedad.

14. INSPECCIÓN
El Subcontratista será responsable de inspeccionar cualquier trabajo de otro subcontratista que pueda afectar su propio Trabajo e informará por escrito cualquier defecto antes de comenzar, o se considerará que aceptó dicho trabajo como correcto. De lo contrario, a opción del Contratista General, volverá a realizar su Trabajo a su propio costo.

15. PROVEEDORES DEL SUBCONTRATISTA
El Subcontratista proporcionará los nombres y direcciones de sus proveedores cuando se le solicite. Si las cuentas con sus proveedores tienen más de quince (15) días de retraso, el Contratista General podrá retener pagos y pagar directamente a los proveedores (incluso mediante cheque conjunto) para poner al día las cuentas. Cualquier resto se pagará al Subcontratista.

16. CONTRATISTA INDEPENDIENTE
El Subcontratista certifica que es un "contratista independiente" y no un empleado del Contratista General, y es el único responsable de todos los impuestos y cargos aplicables (retenciones fiscales, seguridad social y desempleo). El Subcontratista no está bajo la dirección y el control del Contratista General, puede contratar con otras empresas, utiliza sus propias herramientas y oficinas, y nunca habrá una relación de empleador/empleado con el Contratista General.

17. OTROS CONTRATOS
El Contratista General se reserva el derecho de celebrar otros contratos. El subcontratista cooperará con los demás contratistas y les dará el acceso necesario al lugar de trabajo.

18. EMPLEADOS, SUBCONTRATISTAS Y AGENTES DEL SUBCONTRATISTA
a. DISCIPLINA Y CONTROL: El Subcontratista mantendrá estricta disciplina entre sus empleados, subcontratistas y agentes y no empleará a personas no aptas. Si el proyecto es una residencia y el Subcontratista es una Compañía de Servicios a Domicilio o de Entrega Residencial bajo el Código de Prácticas y Remedios Civiles de Puerto Rico, obtendrá verificación de antecedentes penales de cualquier empleado o agente enviado a entregar, colocar, ensamblar, reparar o instalar un artículo, antes de enviarlo. El subcontratista no enviará a ninguna persona cuya información de antecedentes muestre una condena por delito grave en los 20 años anteriores por: (a) un delito clasificado como (i) contra la persona o la familia, (ii) contra la propiedad, o (iii) indecencia pública; o (b) un delito en otra jurisdicción que se clasificaría así en este estado.
b. LEGALMENTE AUTORIZADO: Todos los empleados, subcontratistas y agentes serán mayores de edad y estarán legalmente autorizados para realizar el Trabajo. El Subcontratista cumplirá con todas las leyes de inmigración, incluida la IRCA: (1) obtendrá Formularios I-9 debidamente completados para todos sus empleados y (2) verificará los números de seguro social y demás documentación. El subcontratista defenderá, eximirá de responsabilidad e indemnizará incondicionalmente al propietario, al contratista general y a sus agentes, directores y empleados por cualquier incumplimiento de este párrafo.
c. CONDICIONES DE TRABAJO: El subcontratista tomará todas las medidas necesarias para la seguridad del proyecto y del sitio, incluyendo: (i) informar inmediatamente cualquier práctica o condición de trabajo insegura; y (ii) proporcionar procedimientos de trabajo seguros, equipos, capacitación y supervisión para sus empleados, subcontratistas y agentes.
d. NO DISCRIMINACIÓN: El subcontratista no discriminará a ningún empleado o solicitante por motivos de raza, religión, sexo, color u origen nacional, tomará medidas afirmativas en el empleo, e insertará estas disposiciones en todos sus subcontratos.
e. CUMPLIMIENTO DE OSHA: El subcontratista cumplirá con la Ley de Salud y Seguridad Ocupacional (OSHA) de 1970 y todas las reglas aplicables, incluyendo la Norma de comunicación de peligros (y la entrega de Hojas de Datos de Seguridad), la Protección contra Caídas en la construcción, y la notificación inmediata de cualquier lesión o muerte relacionada con el trabajo.
f. RESPONSABILIDAD TOTAL: El subcontratista asume plena responsabilidad por todos los actos, negligencias u omisiones de sus empleados, agentes y subcontratistas, y de todas las personas que realicen trabajo bajo contrato con el Subcontratista.
g. SUBCONTRATISTAS DEL SUBCONTRATISTA: El subcontratista no empleará a ningún subcontratista, proveedor u otra persona contra quien el Contratista General o su(s) cliente(s) puedan tener objeción.
h. DERECHO A EXCLUIR: El Contratista General tiene derecho a excluir del proyecto a uno o más empleados, agentes o subcontratistas del Subcontratista, por cualquier motivo, y el Subcontratista los reemplazará prontamente.

19. RESPONSABILIDADES GENERALES DEL SUBCONTRATISTA
a. SUPERVISIÓN DEL TRABAJO: El Subcontratista supervisará y dirigirá el Trabajo con la mejor habilidad y atención, y será el único responsable de todos los medios, métodos, técnicas, seguridad, secuencias y procedimientos.
b. REGISTRO FEDERAL: Todos los participantes en el programa GLO-CDR deben tener un número DUNS y un código CAGE.
c. INFORMACIÓN: El Subcontratista proporcionará canales abiertos de comunicación entre el Contratista General y los Inspectores.
d. MANO DE OBRA: El Contratista proporcionará personal competente y debidamente calificado.
e. ORDEN: El Contratista mantendrá en todo momento buena disciplina y orden en el(los) sitio(s).
f. SERVICIOS, MATERIALES Y EQUIPOS: El subcontratista proporcionará y asumirá total responsabilidad por todos los servicios, materiales, equipos, mano de obra, transporte, herramientas, combustible, energía, agua, instalaciones sanitarias y demás elementos necesarios para la ejecución y finalización del Trabajo.
g. INCUMPLIMIENTO: Si el Contratista General o su(s) cliente(s) identifican Trabajo que no cumple con los Documentos del Contrato, los requisitos de HUD o de FEMA, el Subcontratista lo corregirá a su cargo.
h. SUBCONTRATISTAS: El subcontratista celebrará acuerdos escritos con todos sus subcontratistas y proveedores que los vinculen a los Documentos del Contrato y al Contrato Principal, en beneficio del Contratista General y su(s) cliente(s).
i. CONTINUACIÓN DEL TRABAJO: El Subcontratista continuará con el Trabajo y cumplirá con el cronograma durante todas las disputas, salvo indicación escrita en contrario del Contratista General.
j. OTRAS AUTORIDADES: Los deberes enumerados se suman a los demás deberes especificados en este Acuerdo.

20. REGALÍAS Y TARIFAS DE LICENCIA
El Subcontratista pagará todas las regalías y tarifas de licencia necesarias, defenderá todas las acciones por infracción de derechos de autor o patente y eximirá de responsabilidad al Contratista General.

21. SIN DAÑOS POR DEMORA
El Subcontratista no tendrá ningún reclamo por compensación monetaria o daños por demora u obstáculos al Trabajo por cualquier causa, incluido cualquier acto u omisión del Contratista General y/o su(s) Cliente(s).

22. TERMINACIÓN
El Contratista General podrá, en cualquier momento y por cualquier motivo, rescindir este Acuerdo con al menos cinco (5) días de notificación previa al Subcontratista. Si el Subcontratista incurre en alguna violación de este Acuerdo, el Contratista General podrá rescindirlo inmediatamente, sin que el Subcontratista tenga derecho a pago alguno.

23. ACUERDO DE INDEMNIZACIÓN
El subcontratista acepta defender, eximir de responsabilidad e indemnizar incondicionalmente al propietario y al contratista general, sus empresas matrices, subsidiarias y relacionadas, los clientes del contratista general, y sus agentes, propietarios y empleados ("indemnizado"), contra toda responsabilidad, costos, gastos (incluidos honorarios de abogados y expertos), multas, sanciones, pérdidas, reclamaciones y daños que surjan del trabajo realizado, independientemente de si se basan en: (1) la negligencia de cualquier indemnizado, sola, conjunta o concurrente; (2) la negligencia grave del indemnizado; (3) responsabilidad estricta; (4) incumplimiento de cualquier ley de OSHA, federal, estatal o local relacionada con salud y seguridad; o (5) incumplimiento de garantía. La seguridad del lugar de trabajo, de los empleados y del equipo del subcontratista son responsabilidad exclusiva del subcontratista. Estas obligaciones de indemnización y defensa se extenderán a reclamos que ocurran después de la terminación del acuerdo. El subcontratista reconoce que está indemnizando al contratista general por su negligencia única y parcial.

24. AVISOS
En la medida en que la ley no exija lo contrario, los avisos deben realizarse por escrito y entregarse por correo certificado con acuse de recibo o por fax a la dirección de cada parte indicada en este documento.

25. RESOLUCIÓN ALTERNATIVA DE DISPUTAS
Las partes acuerdan que las transacciones contempladas involucran el comercio interestatal.
a. MEDIACIÓN O ARBITRAJE ENTRE CONTRATISTA GENERAL Y PROPIETARIO/CLIENTE: El Subcontratista aceptará y participará en cualquier mediación o arbitraje entre el Contratista General y cualquier Propietario/Cliente si así lo solicita el Contratista General.
b. MEDIACIÓN O ARBITRAJE ENTRE CONTRATISTA GENERAL Y SUBCONTRATISTA: Cualquier disputa (contractual, de garantía, agravio, estatutaria o de otro tipo) se someterá primero a mediación y, si no se resuelve, a arbitraje vinculante según la Ley Federal de Arbitraje (9 U.S.C. §§ 1 et seq.) y no ante un tribunal. El árbitro decidirá la arbitrabilidad y podrá otorgar honorarios y gastos razonables de abogados. Las partes seleccionarán de buena fe un mediador y, de ser necesario, un árbitro en el condado donde se ubica la propiedad. Si no llegan a un acuerdo, se utilizará la Asociación Americana de Arbitraje (AAA); si la AAA no puede actuar, cualquier parte puede solicitar a un tribunal de jurisdicción general que nombre un mediador o árbitro.
c. ARBITRAJE: En cualquier procedimiento: (i) se aplicarán todas las leyes federales y estatales; (ii) se aplicarán todos los reclamos, recursos y defensas disponibles en el tribunal; (iii) será conducido por un único árbitro neutral; (iv) el árbitro será un abogado con licencia en Puerto Rico, en buena reputación y con experiencia significativa en construcción; (v) las partes tendrán derecho a pruebas razonables; (vi) el árbitro dictará un laudo escrito y motivado si se solicita; y (vii) el laudo será definitivo y vinculante.
d. SUPERVIVENCIA: Los derechos y obligaciones de las disposiciones de mediación/arbitraje sobrevivirán a la terminación o incumplimiento del Acuerdo. La invalidez de cualquier parte no afectará el resto. El Contratista General tendrá la opción de incluir al Subcontratista como parte en cualquier mediación o arbitraje entre el Contratista General y un Propietario o Cliente.

26. CONFIDENCIALIDAD Y NO DIVULGACIÓN
Toda la información, informes y registros relacionados con el desempeño bajo este Acuerdo serán propiedad exclusiva y confidencial del Contratista General y no serán divulgados sin su consentimiento previo por escrito. El Subcontratista no utilizará dicha información en beneficio propio o de terceros. En caso de incumplimiento, el Subcontratista será responsable ante el Contratista General por una suma estipulada equivalente a todas las sumas pagadas al Subcontratista bajo este Acuerdo, sin perjuicio del derecho del Contratista General a obtener órdenes de restricción o mandatos judiciales.

27. QUIEBRA O INSOLVENCIA DEL SUBCONTRATISTA
Si el Subcontratista se declara insolvente o en quiebra, admite incapacidad de pagar sus deudas, hace una transferencia en beneficio de acreedores, solicita el nombramiento de un custodio o fideicomisario, inicia un procedimiento de insolvencia o reorganización, sufre una sentencia o embargo no anulado dentro de diez (10) días, o se niega a proporcionar suficientes trabajadores o materiales, no paga a tiempo, o viola cualquier disposición de este Acuerdo, el Contratista General podrá, tras notificación por escrito de cinco (5) días, rescindir este Acuerdo, tomar posesión del Proyecto y los materiales y terminar la Obra de la forma más eficiente. En tal caso, el Subcontratista no tendrá derecho a recibir ningún pago adeudado.

28. OTRAS DISPOSICIONES
a. INVALIDEZ: Si alguna cláusula contraviene o es inválida según las leyes de Puerto Rico, ello no invalidará el Acuerdo completo, que se interpretará como si no contuviera la cláusula inválida.
b. GÉNERO: Los términos "Contratista General", "Subcontratista", "Cliente", "Propietario" incluyen singular o plural, individuo, sociedad o corporación, y sus respectivos herederos, sucesores y cesionarios. Si más de una parte es nombrada como Subcontratista, la obligación es solidaria.
c. ACUERDO VINCULANTE: Los Documentos del Contrato son complementarios. Este Acuerdo permanecerá en pleno vigor desde la fecha de ejecución hasta que se rescinda por escrito, y será vinculante para las partes, sus herederos, sucesores y cesionarios. Ninguno de los derechos u obligaciones puede ser asignado o delegado sin consentimiento; cualquier supuesta transferencia será nula.
d. ASIGNACIÓN (ASSIGNMENT): El Subcontratista no asignará este Acuerdo ni ningún pago adeudado sin el consentimiento previo por escrito del Contratista General. El consentimiento puede negarse por cualquier motivo. Cualquier asignación no autorizada será nula.
e. ACUERDO COMPLETO: Este Acuerdo contiene el acuerdo completo entre las partes, EXCEPTO cualquier Anexo requerido bajo Programas específicos (incluidos los regidos por la Oficina General de Tierras de Puerto Rico y la Ciudad de Houston). Ninguna declaración oral o escrito previo no incorporado tendrá efecto. Ninguna modificación será vinculante salvo que se establezca en un documento ejecutado por todas las partes. En caso de conflicto, prevalecerán los términos de este Acuerdo.
f. NO HAY TERCEROS BENEFICIARIOS: Ninguna cláusula se interpretará para crear derechos en terceros.
g. EL TIEMPO ES ESENCIAL: El tiempo es esencial en el cumplimiento de las obligaciones del Subcontratista. Al vencimiento o terminación, el Subcontratista desalojará de inmediato el lugar de trabajo y retirará sus suministros, herramientas o equipos.
h. LEYES APLICABLES: Las leyes del Estado de Puerto Rico regirán la validez, cumplimiento e interpretación de este Acuerdo. Las partes consienten a Puerto Rico como lugar para cualquier acción. La regla de interpretar la ambigüedad contra la parte redactora no se empleará.
i. PARTES OBLIGADAS: La ejecución de este Acuerdo por cada parte vincula a la entidad representada, así como a sus empleados, agentes, sucesores y cesionarios.

GARANTÍA PERSONAL: Yo/Nosotros garantizamos personal e incondicionalmente el pago completo y puntual a todos los empleados, agentes, subcontratistas, proveedores de materiales y proveedores de mano de obra del Subcontratista.`;
